services:
  backend_py:
    build:
        context: ./backend_py
        dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend_py:
      build:
          context: ./frontend_py
          dockerfile: Dockerfile
      ports:
          - "8501:8501"
  backend_cs:
    build:
        context: ./backend_cs
        dockerfile: Dockerfile
    ports:
      - "8001:8000"

  frontend_cs:
      build:
          context: ./frontend_cs
          dockerfile: Dockerfile
      volumes:
          - keys:/app/keys
      ports:
          - "8502:8501"
volumes:
  keys: {}